name: Release

permissions:
  contents: write

on:
    workflow_dispatch: # 允许手动触发
    push:
        branches:
        - main # 监听 main 分支

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 获取当前和上一个标签
        id: get_tags
        run: |
          git fetch --prune --unshallow
          git tag -l --sort=-version:refnam
          tags=($(git tag -l --sort=-version:refname))
          current_tag=${tags[0]}
          previous_tag=${tags[1]}
          echo "previous_tag=$previous_tag" >> $GITHUB_OUTPUT
          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT
